name: Bleef
version: '${version}'
main: com.foxcqrn.bleef.Bleef
authors: [ hotgothgirl, foxcqrn ]
description: Backslash BungeeCord extension
commands:
  creative:
    description: 'Teleport to creative world'
    usage: '/creative'
    aliases: [ c ]
  survival:
    description: 'Teleport to survival world'
    usage: '/survival'
    aliases: [ s ]
