name: Bleef
version: '1.0.20'
main: com.foxcqrn.bleef.Bleef
api-version: 1.20
authors: [ hotgothgirl, ashduino101 ]
description: core plugin for Backslash server network
depend: [ProtocolLib]
commands:
  afk:
    description: 'Toggle AFK status'
  togglecoords:
    description: 'Toggle XYZ coordinates shown on the action bar'
    aliases: [tc, coords]
  playerstats:
    description: 'View info about a player'
    aliases: [ pstats, pinfo, ps, pi ]
  housemarker:
    description: 'Create/delete your house marker on the dynmap'
    usage: '/housemarker <create|delete>'
    aliases: [ hm ]
  addroad:
    description: 'Create road map line'
    aliases: [ road ]
  addborder:
    description: 'Create border map line'
    aliases: [ border ]
  mapline:
    description: 'Actively maps a line on the Dynmap'
    aliases: [ ml ]
  color:
    description: 'Set custom name hex color'
    usage: '/color <#hex>'
    aliases: [setcolor]
  nickname:
    description: 'Set custom nickname'
    usage: '/nickname <name>'
    aliases: [nick, name, setname, setnick, nn]
  sudo:
    description: 'Run command as user'
    usage: '/sudo <username> <command>'
  creative:
    description: 'Teleport to creative world'
    usage: '/creative'
    aliases: [ c ]
  survival:
    description: 'Teleport to survival world'
    usage: '/survival'
    aliases: [ s ]
  list:
    description: 'Lists server members'
    usage: '/list'
    aliases: [ online ]
  speed:
    description: 'Set movement speed'
    usage: '/speed <value>'
  teleport:
    description: 'Teleport to a server member'
    usage: '/teleport <username>'
    aliases: [ tp ]
  sequence:
    description: 'Plays an OnlineSequencer sequence in-game.'
    usage: '/sequence <sequence_id|stop>'
    aliases: [ play ]
  addhorse:
    description: 'Registers the horse a player is riding to the player.'
    usage: '/addhorse'
  delhorse:
    description: 'Unregisters the horse for a player.'
    usage: '/delhorse'
  map:
    description: 'Show map link'
    usage: '/map'
  wrench:
    description: 'Get a wrench'
    usage: '/wrench'
    aliases: [ givewrench ]
permissions:
  bleef.mapdraw:
    description: 'Allows access to map editing commands'
    default: op
  bleef.wrench.*:
    description: 'Gives full wrench permission'
    default: false
    children:
      bleef.wrench.give: true
      bleef.wrench.bypass: true
  bleef.wrench.give:
    description: 'Allows access to /wrench'
    default: op
  bleef.wrench.bypass:
    description: 'Bypass wrench block blacklist'
