name: Bleef
version: '1.0.21'
main: com.foxcqrn.bleef.Bleef
api-version: 1.21
authors: [ hotgothgirl, ashduino101 ]
description: core plugin for Backslash server network
softdepend: [ProtocolLib]
permissions:
  bleef.mapdraw:
    description: 'Allows access to map editing commands'
    default: op
  bleef.wrench.*:
    description: 'Gives full wrench permission'
    default: false
    children:
      bleef.wrench.give: true
      bleef.wrench.bypass: true
  bleef.wrench.give:
    description: 'Allows access to /wrench'
    default: op
  bleef.wrench.bypass:
    description: 'Bypass wrench block blacklist'
